OneToManyModel/Controllers/ManageCallDataController.cs
using System;
using System.Collections.Generic;
using System.Web.Mvc;

namespace CATS_Interview.Controllers
{
    public class ManageCallDataController : Controller
    {
        //
        // GET: /ManageCallData/
        [HttpGet]
        public ActionResult Index()
        {
            var service = new Services.Service();
            return View(service.GetSummaryOfCalls());
        }

        [HttpPost]
        public ActionResult Index(IEnumerable<DateTime?> selectedCalls, DateTime resetDate)
        {
            var service = new Services.Service();
            try
            {
                if (selectedCalls != null)
                    service.UpdateCalls(selectedCalls, resetDate);
            }
            catch (Exception exception)
            {
                var errorInfo = new HandleErrorInfo(exception, "Interview", "Index");
                return View("Error", errorInfo);
            }
            return View(service.GetSummaryOfCalls());
        }
    }
}

OneToManyModel/Views/Shared/_Layout.cshtml
@using System.Web.Optimization
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title</title>
    <meta name="viewport" content="width=device-width" />
    @Styles.Render("~/Content/themes/custom/AllCss")

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryui")
    @Scripts.Render("~/bundles/jqueryval")
    
    @RenderSection("Head")
</head>
<body>

    <header>
        <div class="content-wrapper">
            <div class="header">
                <div class="lineBreak"></div>
                <img alt="Road Transport Media" src="~/Content/themes/custom/images/Operator-Interview.jpg" />

                <div class="lineBreak"></div>
                <nav>
                    <ul id="menu">
                        <li>@Html.ActionLink("Manage Calls", "Index", "ManageCallData")</li>
                        <li style="visibility: @ViewBag.Hidden">@Html.ActionLink("Update Record", "", "", new { @class = "processRecord" })</li>
                    </ul>
                </nav>
                <div class="lineBreak"></div>
            </div>
        </div>
    </header>


    <div id="body">
        <section class="content-wrapper main-content">
            @RenderBody()
        </section>
    </div>

    <footer>
        <div class="content-wrapper">
            <div>
                <p>&copy; @DateTime.Now.Year - Road Transport Media.</p>
            </div>
        </div>
    </footer>
</body>
</html>